dataset:
  root_dir:
    local: "~/Projects/advanced-neural-networks/data"
    cloud: "/home/jupyter-iroy2/advanced-neural-networks/data/"
  train_metadata: "mnist_train_metadata.csv"
  test_metadata: "mnist_test_metadata.csv"
  download: True
  dataset_statistics:
    mean: 0.1307
    std: 0.3081

model:
  lenet:
    input_shape: [1, 1, 28, 28]
    n_conv_blocks: 2
    out_channels_list: [6, 16]
    kernel_size: 5
    pool_size: 2
    n_linear_layers: 1
    n_neurons_list: [10]

train_config:
  lr: 0.0002
  max_epochs: 20
  optimizer: "adam"
  loss: "bce"
